### ISSUE TITLE
Adding a minimal working example for GLX with X11

### ISSUE THREAD

**Issue by Scylardor** [Dav1dde/glad#107]
Hello,
please, could you add a simple C++ example program of GLAD working with GLX and a simple X lib window in the example folder ?

I have much trouble trying to do just that, and no luck searching.
As soon as I include glad_glx.h instead of the GL/gl.h and glx.h classic headers in a X11 project, it immediately crashes (segmentation fault), because glad re-#defines all the glX functions (eg. glXQueryVersion), and they become uninitialized function pointers when including glad_glx.h.

Calling gladLoadGLX(<my_display>, <my_screen>) doesn't help...
But glXQueryVersion is one of the very first things my program does, so I need it working. What should I do ? I'm a bit lost.

I tried to isolate the issue in a minimal example but came across other problems.

I started from the minimal OpenGL + X11 program found [here](https://www.opengl.org/discussion_boards/showthread.php/165856-Minimal-GLX-OpenGL3-0-example?p=1178905&viewfull=1#post1178905), which works well.

But trying to add Glad to the mix, it doesn't compile anymore (more details below).
I generated glad GLX 1.4 debug files with the web interface. But trying to compile with them throws me compile errors like `undefined reference to 'glad_debug_glClearColor'` and `undefined reference to 'glad_debug_glClear'`.

What can I do from here ? If I try to add, for instance, an OpenGL 4.5 Core glad.c to the project, I now have errors because of `multiple definitions of glad_set_pre_callback`, because both the glad.c and glad_glx.c will define it...

Can you help me understand how to use glad in this situation ?
If I can get it working I'd even be glad (ha!) to make a PR to add it to the example/ folder myself !

---------------------------------
To quickly reproduce:
 my failing compile command is like `g++ glad/src/glad_glx.c glad/glad.c gl3.cpp -o gl3 -lX11 -lGL -ldl -I glad/include -I.`

and here's the full copy of the working minimal example of opengl.org (save as gl3.cpp and compile with "g++ gl3.cpp -o gl3 -lX11 -lGL":
```
#include <GL/glx.h>
#include <GL/gl.h>
#include <unistd.h>
#include <iostream>
 
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
 
#define GLX_CONTEXT_MAJOR_VERSION_ARB       0x2091
#define GLX_CONTEXT_MINOR_VERSION_ARB       0x2092
typedef GLXContext (*glXCreateContextAttribsARBProc)(Display*, GLXFBConfig, GLXContext, Bool, const int*);
 
int main (int argc, char ** argv)
{
    Display *display = XOpenDisplay(0);
 
    glXCreateContextAttribsARBProc glXCreateContextAttribsARB = NULL;
 
    const char *extensions = glXQueryExtensionsString(display, DefaultScreen(display));
    std::cout << extensions << std::endl;
 
    static int visual_attribs[] =
    {
        GLX_RENDER_TYPE, GLX_RGBA_BIT,
        GLX_DRAWABLE_TYPE, GLX_WINDOW_BIT,
        GLX_DOUBLEBUFFER, true,
        GLX_RED_SIZE, 1,
        GLX_GREEN_SIZE, 1,
        GLX_BLUE_SIZE, 1,
        None
     };
 
    std::cout << "Getting framebuffer config" << std::endl;
    int fbcount;
    GLXFBConfig *fbc = glXChooseFBConfig(display, DefaultScreen(display), visual_attribs, &amp;fbcount);
    if (!fbc)
    {
        std::cout << "Failed to retrieve a framebuffer config" << std::endl;
        return 1;
    }
 
    std::cout << "Getting XVisualInfo" << std::endl;
    XVisualInfo *vi = glXGetVisualFromFBConfig(display, fbc[0]);
 
    XSetWindowAttributes swa;
    std::cout << "Creating colormap" << std::endl;
    swa.colormap = XCreateColormap(display, RootWindow(display, vi->screen), vi->visual, AllocNone);
    swa.border_pixel = 0;
    swa.event_mask = StructureNotifyMask;
 
    std::cout << "Creating window" << std::endl;
    Window win = XCreateWindow(display, RootWindow(display, vi->screen), 0, 0, 100, 100, 0, vi->depth, InputOutput, vi->visual, CWBorderPixel|CWColormap|CWEventMask, &amp;swa);
    if (!win)
    {
        std::cout << "Failed to create window." << std::endl;
        return 1;
    }
 
    std::cout << "Mapping window" << std::endl;
    XMapWindow(display, win);
 
    // Create an oldstyle context first, to get the correct function pointer for glXCreateContextAttribsARB
    GLXContext ctx_old = glXCreateContext(display, vi, 0, GL_TRUE);
    glXCreateContextAttribsARB =  (glXCreateContextAttribsARBProc)glXGetProcAddress((const GLubyte*)"glXCreateContextAttribsARB");
    glXMakeCurrent(display, 0, 0);
    glXDestroyContext(display, ctx_old);
 
    if (glXCreateContextAttribsARB == NULL)
    {
        std::cout << "glXCreateContextAttribsARB entry point not found. Aborting." << std::endl;
        return false;
    }
 
    static int context_attribs[] =
    {
        GLX_CONTEXT_MAJOR_VERSION_ARB, 3,
        GLX_CONTEXT_MINOR_VERSION_ARB, 0,
        None
    };
 
    std::cout << "Creating context" << std::endl;
    GLXContext ctx = glXCreateContextAttribsARB(display, fbc[0], NULL, true, context_attribs);
    if (!ctx)
    {
        std::cout << "Failed to create GL3 context." << std::endl;
        return 1;
    }
 
    std::cout << "Making context current" << std::endl;
    glXMakeCurrent(display, win, ctx);
 
        glClearColor (0, 0.5, 1, 1);
        glClear (GL_COLOR_BUFFER_BIT);
        glXSwapBuffers (display, win);
 
        sleep(1);
 
        glClearColor (1, 0.5, 0, 1);
        glClear (GL_COLOR_BUFFER_BIT);
        glXSwapBuffers (display, win);
 
        sleep(1);
 
    ctx = glXGetCurrentContext();
    glXMakeCurrent(display, 0, 0);
    glXDestroyContext(display, ctx);
}
```

**Comment by Dav1dde** [comment]
Hey,

Thanks for the starting points, I will add an example (PR obvioulsy appreciated)!

Looking quickly through the code, before calling `glXQueryExtensionsString` you need to initialize glad_glx using `gladLoadGLX` to fill all function pointers. Then after `glXMakeCurrent` you need to initialize all gl function pointers with `gladLoadGL`.

>I generated glad GLX 1.4 debug files with the web interface. But trying to compile with them throws me compile errors like undefined reference to 'glad_debug_glClearColor' and undefined reference to 'glad_debug_glClear'.

You added glad_glx.{c,h} and glad.{c,h} or just glad_glx?

> multiple definitions of glad_set_pre_callback

This is unfortunately a bug I don't intend to fix in this version of glad (since it would result in an even bigger mess in glad) - Workaround: Don't use the `C/C++ Debug` generator for anything but GL.

I'll try to look into it and get a working example running this weekend. If you want to get it to work now, I would start by only trying to load `glad_glx{c,h}`, then if that works add `glad.{c,h}`.

**Comment by Scylardor** [comment]
> You added glad_glx.{c,h} and glad.{c,h} or just glad_glx?

That was using just the files generated for GLX, ie. **glad_glx.{c,h}**. Actually, I later added a Debug OpenGL 4.5 Core **glad.h**, because **glad_glx.h** makes a `#include <glad/glad.h>`, but this **glad.h** isn't part of the bundle generated by the website when you generate GLX files, so obviously you have to generate and add it separately.

> This is unfortunately a bug I don't intend to fix in this version of glad (since it would result in an even bigger mess in glad) - Workaround: Don't use the C/C++ Debug generator for anything but GL.

I'm going to try that and look how that works. Thanks!

**Comment by Scylardor** [comment]
I've put together the simplest example but it keeps crashing.

Here's the code I use :
```
  //  #include <GL/glx.h>
   // #include <GL/gl.h>
#include <glad/glad_glx.h>
    #include <unistd.h>
    #include <iostream>
     
    #include <stdlib.h>
    #include <string.h>
    #include <stdio.h>
    
    int main (int argc, char ** argv)
    {
        Display *display = XOpenDisplay(0);
        int screen = DefaultScreen(display);

        printf("debug 1: display %p screen %d glXQueryVersion %p\n", display, screen, glXQueryVersion);

        if (!gladLoadGLX(display, screen))
        {
            std::cout << "Error: glad failed to initialize" << std::endl;
            return 1;
        }

        printf("debug 2: display %p screen %d glXQueryVersion %p\n", display, screen, glXQueryVersion);

       
        int major, minor;
        glXQueryVersion(display, &major, &minor); // <------ CRASH HERE

        printf("debug 3: display %p screen %d glXQueryVersion %p\n", display, screen, glXQueryVersion);

        // ...

    }
```

Output:

```
debug 1: display 0x10d3c20 screen 0 glXQueryVersion (nil)
debug 2: display 0x10d3c20 screen 0 glXQueryVersion 0x7fc25f019bb0
Segmentation fault (core dumped)
``` 

The gdb stacktrace is odd, it's like glad successfully initialized glx function pointers, but calling them was still invalid.

```
debug 1: display 0x6c9c20 screen 0 glXQueryVersion (nil)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
debug 2: display 0x6c9c20 screen 0 glXQueryVersion 0x7ffff63a7bb0

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff63a7bb0 in ?? ()
(gdb) backtrace
#0  0x00007ffff63a7bb0 in ?? ()
#1  0x000000000047afb9 in main (argc=1, argv=0x7fffffffde18) at gl3.cpp:28
```

From there, I don't have the slightest idea what could be wrong. Like you suggested I replaced debug GLX files by regular ones and kept the debug GL ones.

**Comment by Dav1dde** [comment]
That doesn't really make sense, mhh:

```c
static void find_coreGLX(Display *dpy, int screen) {
	int major = 0, minor = 0;
	if(dpy == 0 && GLADGLXDisplay == 0) {
		dpy = XOpenDisplay(0);
		screen = XScreenNumberOfScreen(XDefaultScreenOfDisplay(dpy));
	} else if(dpy == 0) {
		dpy = GLADGLXDisplay;
		screen = GLADGLXscreen;
	}
	glXQueryVersion(dpy, &major, &minor);
	GLADGLXDisplay = dpy;
	GLADGLXscreen = screen;
	GLAD_GLX_VERSION_1_0 = (major == 1 && minor >= 0) || major > 1;
	GLAD_GLX_VERSION_1_1 = (major == 1 && minor >= 1) || major > 1;
	GLAD_GLX_VERSION_1_2 = (major == 1 && minor >= 2) || major > 1;
	GLAD_GLX_VERSION_1_3 = (major == 1 && minor >= 3) || major > 1;
}
```
glad calls that exact function when initializing GLX, maybe step through the function (find_coreGLX) and verify that the function pointer you call is at the same address as the function does?

Don't have another idea right now, I'd need to test it myself ... hopefully this weekend.

**Comment by Scylardor** [comment]
Indeed this is strange.
I digged into glad code and it does indeed work _inside_ gladLoadGLX. The function pointer address is the same. But once we're out: segfault.

But wait there's more.
I tried to basically copy/paste gladLoadGLX inside my main.cpp, and... it didn't crash!
But subsequent calls to glX* functions _**still**_ crash after that.

So glad function pointers is only valid as long as libGL is `dlopen`'ed (ie. we're inside `if (open_gl()) ...` code). Once the lib is `dlclose`'d in the `gladLoadGLX`'s `close_gl`, you can't use them anymore (or so it seems).

The lib GL gets completely unloaded on `dlclose`. I wonder if glad is linking against the right GL library.

Another thing that puzzles me is that although I'm linking with -lGL,  `ldd gl3` doesn't show libGL in the libraries list... (I can't post the exact output right now)

I'll check back tonight, but this issue is most likely related to dlopen/dlclose and the libGL I'm using.

**Comment by Scylardor** [comment]
well I had no luck. It does seem caused by the `dlclose` of `close_gl` but I haven't found a satisfactory workaround yet. what I tried:

- I tried adding `RTLD_NODELETE` to the `dlopen` flags in glad_glx.c `open_gl` : no more crashes. The problem is that now `close_gl` won't unload libGL data so it causes leaks
- Simply removing the `dlclose` in `close_gl` obviously stops the crashes too, but leaks the libGL pointer too...
- linking with -lGL (I realized that using glad, there is actually no need!), I tried to pass 0 in `open_gl` dlopen: it's supposed to return a handle for the main program, allowing to search in main program symbols and in shared objects loaded at startup. So I hoped that dlsym would allow us to find the symbols loaded via -lGL. But it doesn't work.
Moreover, using glad, it compiles without the -lGL flag, but removing it doesn't fix either.

- I updated mesa drivers just in case (I use a Xubuntu 16.04 LTS), but it didn't fix the issue

I think I tested all I could. Right now a temporary solution would be to alter my glad files to `dlclose` libGL only at program's end (ie. I'd call the close function myself when quitting the program), but it's an hack I'd rather not use.

anyway If you can get an example program working, I'll be very interested !

**Comment by Dav1dde** [comment]
Yeah, this is a problem. Simple solution, use your own loader and manage the scope of the `dlopen` handle yourself.

This is unfortunately caused by one of my bad design decisions on how to include loaders in glad and a badly designed API.

**Comment by Scylardor** [comment]
Don't worry - it's ok.

I worked around this defect with a braindead RAII class that just makes a dlopen with RTLD_LAZY on construction, and dlcloses in destructor.

It works well enough for what I intend to do. 👍
