### ISSUE TITLE
Add OpenCL support to loader

### ISSUE THREAD

**Issue by pdsharma0** [Dav1dde/glad#203]
I couldn't find anything related to OpenCL so I was curious if this is on the roadmap.

**Comment by Dav1dde** [comment]
Glad uses XML files maintained by Khronos to generate code as far as I am aware no such file exists for OpenCL.

The only thing I am aware of is: https://www.khronos.org/registry/OpenCL/xml/cl.xml but it only contains enumerations and extensions - not enough to generate a full API.

**Comment by WeeBull** [comment]
@Dav1dde : Looks like things might have changed since you last looked. Does [this](https://github.com/KhronosGroup/OpenCL-Docs/pull/67) make it possible to support OpenCL?

**Comment by Dav1dde** [comment]
Yeah looks like Glad can just read it and put out working code. I'll see if I get around to adding it this or next week.

**Comment by WeeBull** [comment]
Great. I did have a go myself, but it started having to play in areas which didn't make immediate sense to me.

Happy to test when you've got something.

**Comment by Dav1dde** [comment]
Unfortunately it's not that easy and requires even more XML workarounds:

```xml
        <type category="struct" name="cl_image_desc">
            <member><type>cl_mem_object_type</type>  <name>image_type</name></member>
            <member><type>size_t</type>              <name>image_width</name></member>
            <member><type>size_t</type>              <name>image_height</name></member>
            <member><type>size_t</type>              <name>image_depth</name></member>
            <member><type>size_t</type>              <name>image_array_size</name></member>
            <member><type>size_t</type>              <name>image_row_pitch</name></member>
            <member><type>size_t</type>              <name>image_slice_pitch</name></member>
            <member><type>cl_uint</type>             <name>num_mip_levels</name></member>
            <member><type>cl_uint</type>             <name>num_samples</name></member>
            <!-- Can't properly express this in XML schema yet - use name/ tag to align? -->
            <member>#ifdef __GNUC__
    __extension__   /* Prevents warnings about anonymous union in -pedantic builds */
#endif
    union {
        cl_mem buffer;
        cl_mem mem_object;
    }</member>
```

**Comment by Dav1dde** [comment]
@WeeBull I have a working OpenCL Hello-World with the `glad2-cl` branch (see linked PR), if you wanna test it out.

**Comment by WeeBull** [comment]
@Dav1dde Ok, I'll try to give it a go shortly.

**Comment by WeeBull** [comment]
@Dav1dde Am I meant to be specifying something to avoid the union type?

`➜  galaxy ~/.local/bin/glad --api opencl --extensions="" --out-path glad c
[07.09.2019 20:51:03][DEBUG     ][glad.plugin   ]: loaded language c: <class 'glad.generator.c.__init__.CGenerator'>
[07.09.2019 20:51:03][DEBUG     ][glad.plugin   ]: loaded language rust: <class 'glad.generator.rust.__init__.RustGenerator'>
[07.09.2019 20:51:03][DEBUG     ][glad.plugin   ]: loaded specification glx: <class 'glad.specification.GLX'>
[07.09.2019 20:51:03][DEBUG     ][glad.plugin   ]: loaded specification wgl: <class 'glad.specification.WGL'>
[07.09.2019 20:51:03][DEBUG     ][glad.plugin   ]: loaded specification gl: <class 'glad.specification.GL'>
[07.09.2019 20:51:03][DEBUG     ][glad.plugin   ]: loaded specification vk: <class 'glad.specification.VK'>
[07.09.2019 20:51:03][DEBUG     ][glad.plugin   ]: loaded specification egl: <class 'glad.specification.EGL'>
[07.09.2019 20:51:03][INFO      ][glad          ]: getting 'cl' specification from remote location
[07.09.2019 20:51:03][INFO      ][glad.opener   ]: opening: 'https://raw.githubusercontent.com/KhronosGroup/OpenCL-Docs/master/xml/cl.xml'
[07.09.2019 20:51:03][INFO      ][glad          ]: generating opencl:None/cl=None
[07.09.2019 20:51:03][INFO      ][glad          ]: no explicit version given for api opencl, using Version(major=2, minor=2)
Traceback (most recent call last):
  File "/home/pauls/.local/bin/glad", line 11, in <module>
    load_entry_point('glad==2.0.0b0', 'console_scripts', 'glad')()
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/__main__.py", line 178, in main
    feature_sets = list(select(specification, api, info) for api, info in apis)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/__main__.py", line 178, in <genexpr>
    feature_sets = list(select(specification, api, info) for api, info in apis)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/__main__.py", line 175, in select
    return generator.select(specification, api, info.version, info.profile, extensions, config, sink=logging_sink)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/generator/c/__init__.py", line 299, in select
    return JinjaGenerator.select(self, spec, api, version, profile, extensions, config, sink=sink)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/generator/__init__.py", line 60, in select
    return spec.select(api, version, profile, extensions, sink=sink)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/parse.py", line 664, in select
    result = result.union(found)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/parse.py", line 516, in find
    self._combined.update(self.types)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/util.py", line 127, in memoized
    cache[key] = func(*args, **kwargs)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/parse.py", line 308, in types
    t = Type.from_element(element)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/parse.py", line 776, in from_element
    return factory(element, name, data)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/parse.py", line 831, in factory
    members = [Member.from_element(e) for e in element.findall('member')]
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/parse.py", line 909, in from_element
    type_ = ParsedType.from_element(element)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/util.py", line 127, in memoized
    cache[key] = func(*args, **kwargs)
  File "/home/pauls/.local/lib/python2.7/site-packages/glad/parse.py", line 1127, in from_element
    logger.warn('union type at line %s, TODO: %s', element.sourceline, raw)
AttributeError: sourceline
`

**Comment by WeeBull** [comment]
So, by deleting that union from the XML I've managed to generate some files. I'm a little confused though.

`GLAD_API_CALL int gladLoadOpenCL(cl_device_id device, GLADloadfunc load);`

That appears to need a `cl_device_id`, but before I've loaded the function pointers, how am I supposed to interrogate the system to find which devices exist? Seems like a catch-22 to me.

**Comment by Dav1dde** [comment]
@WeeBull ignore the warning for now, the generated code will compile (you'll just get issues when you want to use the datatype).

The error is because you don't have `lxml` installed, the lxml etree implementation provides a `sourceline` where as the python builtin doesn't (need to fix this).

Just pass `NULL` for the device_id, you'll get all 1.0 functions loaded, which is enough to get a device id, then call the loader again with the device id. For an example see the code in the Pull-Request, there is an example.

**Comment by Dav1dde** [comment]
I've started on this, but I currently don't have the time to finish it and due to low overall interest I'll close this for now
