### ISSUE TITLE
Unable to use glad2 CMake library (Jinja2 attribute issue after update)

### ISSUE THREAD

**Issue by WSSDude420** [Dav1dde/glad#361]
After updating pip packages, glad2 stopped compiling for me with following error:

```
    Traceback (most recent call last):
      File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "C:\git\nJin\dep\glad\glad\__main__.py", line 21, in <module>
        from glad.plugin import find_specifications, find_generators
      File "C:\git\nJin\dep\glad\glad\plugin.py", line 5, in <module>
        from glad.generator.c import CGenerator
      File "C:\git\nJin\dep\glad\glad\generator\c\__init__.py", line 54, in <module>
        @jinja2.contextfunction
    AttributeError: module 'jinja2' has no attribute 'contextfunction'
```

Attribute `contextfunction` was removed and it was apparently replaced by `pass_context` (at least according to [this](https://stackoverflow.com/questions/71634462/why-is-my-flask-app-crashing-with-importerror-cannot-import-name-contextfuncti) when I tried to search for this issue).

**Comment by WSSDude420** [comment]
Small update - tried to replace mentioned function + `contextfilter` by mentioned `pass_context` which according to [official docs](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.pass_context) is truly a replacement in latest Jinja2 and it started working again.
